### ISSUE TITLE
TimeoutError: Connection timed out after 1000ms

### ISSUE THREAD

**Issue by pkaeding** [santthosh/aws-es-kibana#1]
I tried using this, and got the following error:

```
aws-es-kibana https://xxxxxxxxxx.us-east-1.es.amazonaws.com
__________       _________    _________________    ________                            ______
___    |_ |     / /_  ___/    ___  ____/_  ___/    ___  __ \________________  ______  ____  /
__  /| |_ | /| / /_____ \     __  __/  _____ \     __  /_/ /_  ___/  __ \_  |/_/_  / / /_  /
_  ___ |_ |/ |/ / ____/ /     _  /___  ____/ /     _  ____/_  /   / /_/ /_>  < _  /_/ / /_/
/_/  |_|___/|__/  /____/      /_____/  /____/      /_/     /_/    \____//_/|_| _\__, / (_)
                                                                               /____/
AWS ES cluster available at http://127.0.0.1:9200
Kibana available at http://127.0.0.1:9200/_plugin/kibana/
/usr/local/lib/node_modules/aws-es-kibana/index.js:29
    if (err) throw err;
             ^

TimeoutError: Connection timed out after 1000ms
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at ClientRequest.emit (events.js:166:7)
    at Socket.emitTimeout (_http_client.js:542:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:318:8)
    at _runOnTimeout (timers.js:524:11)
```

Any ideas?

(I noticed that you just posted this today-- imagine the chance that I was searching for this very thing, and it appeared today!)

**Comment by mkubenka** [comment]
Try to remove _https://_ part from endpoint:

```
aws-es-kibana xxxxxxxxxx.us-east-1.es.amazonaws.com
```

**Comment by pkaeding** [comment]
Hmm, I still get the same result when I remove the `https://`.

**Comment by mkubenka** [comment]
Do you have correct credentials? Maybe it's related to aws/aws-sdk-js#849

**Comment by pkaeding** [comment]
Ahh, yes, I had slightly different environment variables with my credentials (it seems every aws tool uses slightly different environment variable names or other mechanisms for reading credentials).

Thanks for your help!
