### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by acinader** [santthosh/aws-es-kibana#10]
would be nice if we could (easily) configure for larger payloads?

i'm not that familiar with kibana (yet), but maybe there is a logical value that should be synced?

maybe this helpful?? http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large

```
Error: request entity too large
    at readStream (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/raw-body/index.js:196:17)
    at getRawBody (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/raw-body/index.js:106:12)
    at read (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/body-parser/lib/read.js:76:3)
    at rawParser (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/body-parser/lib/types/raw.js:81:5)
    at Layer.handle [as handle_request] (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/router/index.js:312:13)
    at /Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/user/.nvm/versions/node/v6.2.2/lib/node_modules/aws-es-kibana/node_modules/express/lib/middleware/init.js:33:5)
```

**Comment by acinader** [comment]
this is my problem.
