### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by apremalal** [santthosh/aws-es-kibana#31]
I'm getting the following error. Is there a way to increase the request size?

```
Error: request entity too large
    at readStream (/app/node_modules/raw-body/index.js:196:17)
    at getRawBody (/app/node_modules/raw-body/index.js:106:12)
    at read (/app/node_modules/body-parser/lib/read.js:76:3)
    at rawParser (/app/node_modules/body-parser/lib/types/raw.js:81:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
```

**Comment by jayhilden** [comment]
I'm getting the same error on the kibana page after I set the default index

**Comment by jayhilden** [comment]
if you're running this through docker (like I am) add the following parameter:
```
-e LIMIT=1000kb
```

**Comment by blakeyoder** [comment]
Hi there @apremalal - this fix was merged upstream via https://github.com/santthosh/aws-es-kibana/pull/22

**Comment by apremalal** [comment]
Thanks @blakeyoder appreciate it very much.
