### ISSUE TITLE
Pull request #48 breaks authentication using environment variables

### ISSUE THREAD

**Issue by phillipsnick** [santthosh/aws-es-kibana#50]
This only applies to the master branch.

Was investigating the feasibility of using the basic auth fix under #49 but ran into issues with building/running under docker.

Error log

```
AWS ES cluster available at http://0.0.0.0:9200
Kibana available at http://0.0.0.0:9200/_plugin/kibana/
fs.js:1384
throw error;
^
Error: watch /root/.aws/credentials ENOENT
at _errnoException (util.js:992:11)
at FSWatcher.start (fs.js:1382:19)
at Object.fs.watch (fs.js:1408:11)
at Object.<anonymous> (/app/index.js:219:4)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
```

PR: https://github.com/santthosh/aws-es-kibana/pull/48

Cause: https://github.com/santthosh/aws-es-kibana/commit/2f1f6db0ebeb139e970bf935e861b1d28dfcbf05#diff-168726dbe96b3ce427e7fedce31bb0bcR205

**Comment by juanpanie** [comment]
Hello! Pretty much the same issue here, but not under docker, just basic auth:

AWS ES cluster available at http://127.0.0.1:9200
Kibana available at http://127.0.0.1:9200/_plugin/kibana/
fs.js:1411
    throw error;
    ^

Error: watch /home/tmd/.aws/credentials ENOENT
    at FSWatcher.start (fs.js:1409:19)
    at Object.fs.watch (fs.js:1435:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/index.js:211:4)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)

Any recommendations ?

**Comment by umbobabo** [comment]
Hi,
I had this problem today. I worked it around just creating an empty credentials file.
So in my case I just did from my user folder:
``` mkdir .aws && cd .aws && touch credentials```.

Then run the aws-es-kibana command again and I see everything correctly.
Open this helps at least to unblock someone.

**Comment by pecigonzalo** [comment]
You can also `-v /tmp/dummy:/root/.aws/credentials` with docker
