### ISSUE TITLE
Cannot access url

### ISSUE THREAD

**Issue by pythondata** [santthosh/aws-es-kibana#58]
> npm install -g aws-es-kibana
> aws-es-kibana XXXX.us-west-2.es.amazonaws.com

/usr/local/lib/node_modules/aws-es-kibana/index.js:160
app.use(async function (req, res) {
        ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by malekerramli** [comment]
having same error
