### ISSUE TITLE
Unable to manage mappings via proxy

### ISSUE THREAD

**Issue by nicolai86** [santthosh/aws-es-kibana#6]
POST/ PUT requests fail when using `aws-es-kibana`: 

```
_http_outgoing.js:346
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/index.js:112:14)
    at ProxyServer.emit (/usr/local/lib/node_modules/aws-es-kibana/node_modules/eventemitter3/index.js:119:35)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:115:27)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:541:7)
    at onSocketNT (_http_client.js:553:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by santthosh** [comment]
@nicolai86 Is this still happening with the latest version, can you please advise?

**Comment by jlsalvador** [comment]
Yep (v1.0.5).

```
_http_outgoing.js:367
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ClientRequest.setHeader (_http_outgoing.js:367:11)
    at ProxyServer.<anonymous> (/usr/lib/node_modules/aws-es-kibana/index.js:137:14)
    at ProxyServer.emit (/usr/lib/node_modules/aws-es-kibana/node_modules/eventemitter3/index.js:119:35)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/aws-es-kibana/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:125:27)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:573:7)
    at onSocketNT (_http_client.js:585:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by nicolai86** [comment]
@santthosh I abandoned this package for a golang based alternative which never showed similar issues.

**Comment by nicolai86** [comment]
See https://gist.github.com/nicolai86/5ffe8905ab2c16cf0b3eb8f054bae456

**Comment by santthosh** [comment]
Nice @nicolai86! @jlsalvador will try to fix this ASAP

**Comment by bwalsh** [comment]
+1 Running into the same problem

**Comment by valydia** [comment]
+1
