### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by harishh486** [santthosh/aws-es-kibana#64]
I was using thius library for a while, but suddenly it starts to throw this error:

AWS ES cluster available at http://0.0.0.0:443
Kibana available at http://0.0.0.0:443/_plugin/kibana/
/usr/lib/node_modules/aws-es-kibana/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.socketCloseListener (_http_client.js:400:25)
    at TLSSocket.emit (events.js:333:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:556:7) {
  code: 'ECONNRESET'

Is there a fix for this error?

**Comment by zoellner** [comment]
Are you using aws-cli v2? I'm seeing these issues as well since I updated aws-cli

**Comment by monken** [comment]
I got frustrated with this package so I just released https://github.com/monken/aws4-proxy. Would you mind giving it a try? It has much less dependencies and should hopefully just work for you.

**Comment by harishh486** [comment]
Thanks Moritz,

I ll give a try and let u know. the behaviour.

Thanks


Harish Mandhadi
513-884-5012

**Comment by harishh486** [comment]
Hi moritz,

I was trying this library, and I have my .aws/credentials and I have give
profile as default with role arn.


It is not working for me.

Am i missing something? regarding credentials. I did not use specific
access-key , secret variables in my env. I was trying to get those details
from credential file.
I dont know whether it works or not

Harish Mandhadi
513-884-5012
