### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by parthtrivedi2492** [santthosh/aws-es-kibana#7]
Hello,

I am using aws-es-kibana plugin as proxy for AWS kibana. It works fine for some time but then suddenly I am getting socket hang up error. Any idea?

**Comment by parthtrivedi2492** [comment]
/usr/lib/node_modules/aws-es-kibana/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1528:15)
    at CleartextStream.socketCloseListener (http.js:1578:23)
    at CleartextStream.emit (events.js:95:17)
    at tls.js:694:10
    at process._tickDomainCallback (node.js:492:13)

**Comment by santthosh** [comment]
@parthtrivedi2492  Is this still happening with the latest version, can you please advise on some recreation steps?

**Comment by imre-kerr** [comment]
I am able to reproduce this by aborting any request (e.g. just close browser tab before kibana is fully loaded.) I implemented a simple error handler, this seems to fix it.
