### ISSUE TITLE
no such file or directory, watch '/Users/mehrajuddin/.aws/credentials'

### ISSUE THREAD

**Issue by Mehraj123** [santthosh/aws-es-kibana#71]
Step#1: sudo npm install -g aws-es-kibana
Step#2: export the accessKey and secretKey

Step#3: aws-es-kibana cluster-address

internal/fs/watchers.js:226
    throw error;
    ^

Error: ENOENT: no such file or directory, watch '/Users/mehrajuddin/.aws/credentials'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1582:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-es-kibana/index.js:211:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/Users/mehrajuddin/.aws/credentials',
  filename: '/Users/mehrajuddin/.aws/credentials'

**Comment by jensbodal** [comment]
Try creating that file and just add `[default]` to the top of it
